### ISSUE TITLE
Tracking bugs and features

### ISSUE THREAD

**Issue by teunbrand** [AllanCameron/geomtextpath#8]
It's good that we have identified some issues and ideas that we want to keep track of, but these are currently mentioned all over the place. I thought it could be useful to have a checklist issue to keep track of bugs we're aware of. Plus, it is very satisfying to check off things from a checklist. Feel free to comment additional ones as you encounter them.

# Bugs

- [x] Line breaks don't work (#4).
- [x] Sometimes text flips (https://github.com/AllanCameron/geomtextpath/pull/7#issuecomment-972244862).
- [x] Spacing might be too wide when curvature is variable (https://github.com/AllanCameron/geomtextpath/pull/7#issuecomment-972195921).
- [x] There are no tests for correctness yet (https://github.com/AllanCameron/geomtextpath/issues/1#issue-1053053688).
- [x] Under extreme aspect ratios, all letters of a string could be discarded, leading to errors in `.get_surrounding_lines()`.

# Features

- [x] Alternatively parametrised versions of `geom_textpath()`  (#5).
- [x] Expose the `shape_string(tracking = ...)` argument to user to finetune letter spacing (https://github.com/AllanCameron/geomtextpath/issues/4#issuecomment-970216724).
- [x] A `halign` parameter for alignment of multi-line strings (see [example in comments](https://github.com/AllanCameron/geomtextpath/issues/8#issuecomment-975515969))

**Comment by AllanCameron** [comment]
The latest commit should fix the curvature / spacing problem. It turns out that the spiral is a really useful test - you should notice that this looks nicer at all aspect ratios now if you look at the updated readme.

I have ticked this off the above list, though I wonder if once we are done with the above problems we should just make a separate issue for each.

**Comment by AllanCameron** [comment]
We should now have line breaks implemented:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

spiral <- data.frame(x = rev(sin(seq(0, 5*pi, length.out = 1000)) * 1000:1),
                     y = rev(cos(seq(0, 5*pi, length.out = 1000)) * 1000:1),
                     s = seq(1, 10, length.out = 1000),
                     z = paste("Like a circle in a spiral, like a",
                               "wheel within a wheel, never ending",
                               "or beginning on an ever spinning reel"))

spiral$z <- paste(spiral$z, spiral$z, sep = "\n")

ggplot(spiral, aes(x, y, label = z)) +
  geom_textpath(size = 5, linewidth = 0, vjust = 2) +
  coord_equal(xlim = c(-1500, 1500), ylim = c(-1500, 1500))
```

![](https://i.imgur.com/ogTtTd0.png)

``` r
library(geomtextpath)
#> Loading required package: ggplot2

 ggplot(within(iris, Species <- paste("This is", Species, sep = "\n")), 
        aes(x = Sepal.Length, color = Species)) +
  geom_textpath(aes(label = Species),
                size = 5, stat = "density",
                fontface = 2, hjust = 0.1, vjust = 0.9)
```

![](https://i.imgur.com/b2w8Q01.png)

I've had to split the lines into different groups, each with their own `vjust` to get this to work. This means that each path length is calculated separately, and that can result in the upper and lower lines not centering well with each other the whole way along a path. I'll work on fixing this, though to be honest it's not very aesthetically pleasing to have two or more lines bent along a path.

**Comment by AllanCameron** [comment]
Tracking is now exposed to end users as a "spacing" parameter in geom_textpath:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

ggplot(iris, aes(x = Sepal.Length, color = Species)) +
  geom_textpath(aes(label = Species),
                size = 6, stat = "density",
                fontface = 2, hjust = 0.2)
```

![](https://i.imgur.com/sIRXaLH.png)

``` r
 
 
ggplot(iris, aes(x = Sepal.Length, color = Species)) +
  geom_textpath(aes(label = Species),
                size = 6, stat = "density",
                fontface = 2, hjust = 0.2, spacing = 100)
```

![](https://i.imgur.com/G6E3wag.png)

``` r
ggplot(iris, aes(x = Sepal.Length, color = Species)) +
  geom_textpath(aes(label = Species),
                size = 6, stat = "density",
                fontface = 2, hjust = 0.2, spacing = 1000)
```

![](https://i.imgur.com/AKMuuhF.png)

``` r
  
ggplot(iris, aes(x = Sepal.Length, color = Species)) +
  geom_textpath(aes(label = Species),
                size = 6, stat = "density",
                fontface = 2, hjust = 0.2, spacing = -100)
```

![](https://i.imgur.com/thxRDgu.png)

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by teunbrand** [comment]
Through a stroke of luck in #9, flipping labels are fixed:

``` r
library(geomtextpath)
#> Loading required package: ggplot2
df <- data.frame(x = 1:1000, y = 1, text = "This is a perfectly flat label")

ggplot(df, aes(x, y, label = text)) +
  geom_textpath(size = 6) +
  coord_polar(start = pi)
```

![](https://i.imgur.com/WbI2vgu.png)

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by AllanCameron** [comment]
Sorry about all the automation fails Teun. I now have it so that the readme updates automatically - it's actually quite useful as a visual test following a commit, and I was finding it tiresome to manually knit the rmd every time I committed.

**Comment by teunbrand** [comment]
Nice work with all the tracking, line breaks and automation Allan! Everything seems to be coming along very smoothly!

**Comment by AllanCameron** [comment]
Too soon for a hex sticker? Maybe something like this?
``` r
library(geomtextpath)
#> Loading required package: ggplot2

p <- hexSticker::sticker(
       ggplot(data.frame(x = seq(0, 10, 0.01),
                         y = 10 - sqrt(100 - seq(0, 10, 0.01)^2),
                         label = "geomtextpath"), 
              aes(x, y, label = label)) +
          geom_textpath(vjust = -0.5, size = 12, color = "white") +
          labs(x = "", y = "") +
          scale_y_continuous(breaks = 0:2 * 5, labels = round) +
          scale_x_continuous(breaks = 0:2 * 5, labels = round) +
          hexSticker::theme_transparent() +
          theme(axis.text = element_text(color = "white", size = 20),
                panel.grid = element_blank(),
                axis.ticks = element_blank(),
                axis.line = element_line(color = "white")),
       package = "", s_height = 1.2, s_width = 1.2, 
       s_x = 0.9, s_y = 0.9, h_fill = "#2332A9", h_color = "orange")

p
```

![](https://i.imgur.com/ywiYsmX.png)

<sup>Created on 2021-11-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by teunbrand** [comment]
It would be nice if we can have a `halign` parameter a la {ggtext} for how to handle horizontal justification of multi-line strings.

An example of how the `halign` parameter operates in {ggtext}:

``` r
library(ggtext)
library(ggplot2)

df <- expand.grid(
  x = c(0, 0.5, 1),
  y = c(0, 0.5, 1),
  text = "This is a<br>multi-line<br>string for<br>demonstration."
)

ggplot(df, aes(x = x, y = y, label = text)) +
  geom_textbox(
    aes(hjust  = x,
        halign = y),
    width = unit(1.5, "inch")
  ) +
  geom_point(colour = "red") +
  labs(x = "hjust", y = "halign") +
  scale_y_continuous(expand = c(0.2,0))
```

![](https://i.imgur.com/SUQt0lW.png)

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AllanCameron** [comment]
Yes, I'd had the same thought. The multi-line text support seems disproportionately complex to get right. I'm currently working on a method for allowing flipping of upside-down text, which might make it even harder...

**Comment by teunbrand** [comment]
I think the multi-line support could be relatively straightforward by taking the `y_offset` parameter from `systemfonts::shape_string()`, but it'd take me some time to refactor stuff exactly right. The `halign` could then just be implemented as the `shape_string(hjust = halign)`. I might need to make a separate branch to experiment with this so I don't get a screwed up repo when I commit stuff.

**Comment by AllanCameron** [comment]
It could maybe be easier this way, but it's not the calculation of the correct y position that's the difficult part (I think I have this correctly calculated from the number of lines of text, the vjust and the lineheight). 

The difficult part is that the curvature is different for different lines of text. To preserve the correct letter spacing in different lines we need to work out the curvature for each line of text and correct for it. 

Imagine the text is on the inside of a circle. If you decrease the vjust from 0  to -1, the text moves towards the centre of the circle, and the string squashes in, so you need to account for that by calculating an "adjusted length" - this is the length of the offset path at vjust = -1. That's what we currently do with the curvature calculation. For multi-line text, the natural way to do this is by breaking up the text line by line and calculating the path for each line separately, which is what happens currently.

You may find a creative way round this, but my instinct is that it's inherently complicated. I certainly had a few false starts trying to get it right in the first place.

**Comment by AllanCameron** [comment]
The bugs in this issue are fixed, and the feature requests are now implemented.
